### ISSUE TITLE
install z2mqtt mqtt with home assistant (ember coordinator dongle-e

### ISSUE THREAD

**Issue by TawfikDaim** [TawfikDaim/home_automation#87]
Objective: install fresh firmware on Zigbee dongle as 
1. coordinator
2. Router

https://www.google.com/search?q=z2mqtt+integration+with+homeassistant&rlz=1C1GCEU_enEG1000EG1000&oq=z2mqtt+integration+with+homeassistant&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIJCAEQIRgKGKAB0gEINjY5N2owajSoAgCwAgE&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:8233b13c,vid:N5fSMXZVbT8,st:0

you can get specific version of z2mqtt (for me I used[1.39.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.39.0)) since I susppected an issue with latest one

**Comment by TawfikDaim** [comment]
https://github.com/TawfikDaim/home_automation/issues/85

https://darkxst.github.io/silabs-firmware-builder/

https://github.com/darkxst/silabs-firmware-builder?tab=readme-ov-file

Supported devices:

Sonoff ZBDongle-E
Easyiot ZB-GW04
SMLIGHT SLZB-07
SMLIGHT SLZB-06M
It will install the most recent recommended builds from [darkxst/silabs-firmware-builder](https://github.com/darkxst/silabs-firmware-builder). If you want the very latest builds, you can use Custom URL option.

**Comment by TawfikDaim** [comment]
Flash zigbee dongle-p as router

Adapter:
Sonoff ZB-dongle-P
Firmware
https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_3.x.0/bin
[CC1352P2_CC2652P_launchpad_router_20221102.zip](https://github.com/Koenkk/Z-Stack-firmware/blob/master/router/Z-Stack_3.x.0/bin/**CC1352P2_CC2652P_launchpad_router_20221102.zip**)
https://github.com/Koenkk/Z-Stack-firmware/blob/master/router/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_router_20221102.zip

Tools

    UI tools
        [SMLIGHT firmware updater](https://smlight.tech/flasher/#other_cc) (recommended)
        Allows for flashing your adapter from the browser, eliminating the need for any software installation.
        Texas Instruments [FLASH PROGRAMMER 2](https://www.ti.com/tool/FLASH-PROGRAMMER) (Windows only) (can't find your device? read below!)
        [ZigStar GW Multi tool](https://github.com/xyzroe/ZigStarGW-MT) (multi platform GUI tool)

    CLI tools (multi platform Python based command line tools)
        [CC2538-BSL](https://github.com/JelmerT/cc2538-bsl) ([instructions](https://www.zigbee2mqtt.io/guide/adapters/flashing/flashing_via_cc2538-bsl.html))
        [llama-bsl](https://github.com/electrolama/llama-bsl) (fork of cc2538-bsl with added features)

Resources:

    https://www.zigbee2mqtt.io/guide/adapters/zstack.html
    https://smlight.tech/flasher/#other_cc
    https://www.youtube.com/watch?v=4eYnURcDrWw&t=39s

**Comment by TawfikDaim** [comment]
Target 18/9/2024
1- setup the 2 dongle-p as routers (erase current firmware if needed)
2- connect both as router on Z2mqtt
3- document all steps in details below

**Comment by Ashour-sama** [comment]
### **Update: Sep. 22nd, 2024**

The procedure was done on Windows 11.

Step 1: add drivers -  _**only needed when the device is not recognized in the device manager**_:
[CP210x USB to UART Bridge VCP Drivers](https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers)

First trial: using Texas Instruments [FLASH PROGRAMMER 2]
source: followed this tutorial: [Using Texas Instruments (FLASH PROGRAMMER 2)](https://www.youtube.com/watch?v=4jqQCxjlRDU)
result: it did not work, please check this thread: [Error when flashing the new firmware](https://github.com/Koenkk/Z-Stack-firmware/issues/397)

Second trial: using Python script:
source: followed this tutorial: [Using Python script](https://www.youtube.com/watch?v=4eYnURcDrWw)
result: it showed success.

![Image](https://github.com/user-attachments/assets/69a2b16a-0d3f-4bea-a586-934ebf70773d)

**Comment by TawfikDaim** [comment]
> ### **Update: Sep. 22nd, 2024**
> 
> The procedure was done on Windows 11.
> 
> Step 1: add drivers -  _**only needed when the device is not recognized in the device manager**_:
> [CP210x USB to UART Bridge VCP Drivers](https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers)
> 
> First trial: using Texas Instruments [FLASH PROGRAMMER 2]
> source: followed this tutorial: [Using Texas Instruments (FLASH PROGRAMMER 2)](https://www.youtube.com/watch?v=4jqQCxjlRDU)
> result: it did not work, please check this thread: [Error when flashing the new firmware](https://github.com/Koenkk/Z-Stack-firmware/issues/397)
> 
> Second trial: using Python script:
> source: followed this tutorial: [Using Python script](https://www.youtube.com/watch?v=4eYnURcDrWw)
> result: it showed success.
> 
> ![Image](https://github.com/user-attachments/assets/69a2b16a-0d3f-4bea-a586-934ebf70773d)

Well done 💪
Thank you 

🙏 

Does the router pair with the currrht Zigbee network coordinator? If yes please add screen shot of the map.

**Comment by TawfikDaim** [comment]
Well done 👍 

Is the process that was successful repeatable and will give same results every time ?

**Comment by Ashour-sama** [comment]
Firmware flashing was successful with every dongle flashed, but the pairing only succeeded once due to hardware issues.
You told me, "That one dongle is already fried."

**Comment by Ashour-sama** [comment]
### **Update: Sep. 22nd, 2024**

I tried to upgrade the coordinator to fix the "ember" warning, but all methods I used were in vain.

1- I used [Silabs firmware flasher](https://darkxst.github.io/silabs-firmware-builder/)
result: it said the running firmware can not be detected.

2- I used the same Python script I used yesterday.
result: I got this error [Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'](https://github.com/JelmerT/cc2538-bsl/issues/116)

last resort:
As Tamer, the IT guy is not present, I will ask him tomorrow to get me a screwdriver, so I can manually force the dongle into boot mode, and then I will try the two methods again.

**Comment by TawfikDaim** [comment]
> > ### **Update: Sep. 23rd, 2024**
> > I tried to upgrade the coordinator to fix the "ember" warning, but all methods I used were in vain.
> > 1- I used [Silabs firmware flasher](https://darkxst.github.io/silabs-firmware-builder/)
> > result: it said the running firmware can not be detected.
> > 2- I used the same Python script I used yesterday.
> > result: I got this error [Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'](https://github.com/JelmerT/cc2538-bsl/issues/116)
> > last resort:
> > As Tamer, the IT guy is not present, I will ask him tomorrow to get me a screwdriver, so I can manually force the dongle into boot mode, and then I will try the two methods again.
> 
> Please watch this
> 
> https://youtu.be/r0ihC8Dx3NM?si=AxQVyPPK672ickjh


**One recommendation to fix router firmware on Zigbee Dongle P using Python script on Windows 11 that worked for me** 
- I was getting error 
"Verifying by comparing CRC32 calculations.
    Verified (match: 0x9877ee56)
ERROR: int() can't convert non-string with explicit base"
The solution is in this link: https://github.com/JelmerT/cc2538-bsl/commit/24c9010a570a324a64e79452af4b17b9a5a3d88e#diff-9d6356e73eb9065e1b5a72ad6cfd71d5c08cd22b7be6cb08d6318aa51885a93eL1224
simply change one line in cc2538-bsl.py file, 
        +    if args.ieee_address != 0:
        -     if args.ieee_address:
then rerun the command: e.g. python cc2538-bsl.py -p COM8 -e -v -w --bootloader-sonoff-usb CC1352P2_CC2652P_launchpad_router_20221102.hex

full instructions are in this video https://www.youtube.com/watch?v=4eYnURcDrWw
command used: python cc2538-bsl.py -p COM8 -e -v -w --bootloader-sonoff-usb CC1352P2_CC2652P_launchpad_router_20221102.hex

this also works succesfully to install coordinator firware on Zigbee dongle P
command used: python cc2538-bsl.py -p COM8 -e -v -w --bootloader-sonoff-usb CC1352P2_CC2652P_launchpad_coordinator_20220219.hex

**Comment by TawfikDaim** [comment]
How to put ZbDongle in boot mode without unscrewing using Python
pip install gevent
python uartLog.py

[https://sonoff.tech/wp-content/uploads/2023/02/SONOFF-Zigbee-3.0-USB-dongle-plus-firmware-flashing.pdf]
